import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { StopsProvider } from "@/context/StopsContext";
import { SearchCarProvider } from "@/context/SearchCarContext";
import { SearchCarBodyProvider } from "@/context/SearchCarBodyContext";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
  map,
  panel,
}: {
  children: React.ReactNode;
  map: React.ReactNode;
  panel: React.ReactNode;
}) => {
  return (
    <html lang="ja">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}>
        <StopsProvider>
          <SearchCarProvider>
            <SearchCarBodyProvider>
              <>
                {children}
              </>
              <div className="basis-80 h-[100vh]">
                {panel}
              </div>
              <div className="grow h-[100vh]">
                {map}
              </div>
            </SearchCarBodyProvider>
          </SearchCarProvider>
        </StopsProvider>
      </body>
    </html>
  );
}

export default RootLayout